"""initial schema

Revision ID: bb24d4d489d1
Revises: 
Create Date: 2026-06-17 02:39:34.746976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb24d4d489d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celestial_bodies',
    sa.Column('class_label', sa.String(length=10), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('g', sa.Float(), nullable=False),
    sa.Column('i', sa.Float(), nullable=False),
    sa.Column('objid', sa.Integer(), nullable=False),
    sa.Column('r', sa.Float(), nullable=False),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('redshift', sa.Float(), nullable=False),
    sa.Column('u', sa.Float(), nullable=False),
    sa.Column('z_mag', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('objid')
    )
    op.create_table('curated_celestial_bodies',
    sa.Column('class_label', sa.String(length=10), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('g', sa.Float(), nullable=False),
    sa.Column('gaia_parallax', sa.Float(), nullable=True),
    sa.Column('gaia_pmdec', sa.Float(), nullable=True),
    sa.Column('gaia_pmra', sa.Float(), nullable=True),
    sa.Column('gaia_source_id', sa.Integer(), nullable=True),
    sa.Column('i', sa.Float(), nullable=False),
    sa.Column('objid', sa.Integer(), nullable=False),
    sa.Column('r', sa.Float(), nullable=False),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('redshift', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('u', sa.Float(), nullable=False),
    sa.Column('wise_w1', sa.Float(), nullable=True),
    sa.Column('wise_w2', sa.Float(), nullable=True),
    sa.Column('z_mag', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('objid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curated_celestial_bodies')
    op.drop_table('celestial_bodies')
    # ### end Alembic commands ###
